import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { MantineProvider } from "@mantine/core";
import { theme } from "../config/themeMantine";

import "@mantine/core/styles.css";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<meta name="theme-color" content="#2F3551" />
				<title>Portafolio - Luis Villegas</title>
				{/* <meta
					name="description"
					content="Portafolio de un desarrollador web especializado en React. Explora proyectos innovadores y de alto rendimiento que demuestran habilidades avanzadas en desarrollo frontend y backend, optimización del rendimiento y diseño de interfaces intuitivas."
				/> */}
			</head>
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<MantineProvider theme={theme}>{children}</MantineProvider>
			</body>
		</html>
	);
}
