import { createTheme } from "@mantine/core";
import { colors } from "./colors";

export const theme = createTheme({
	colors: {
		primary: [
			colors.primary,
			colors.primary,
			colors.primary,
			colors.primary,
			colors.primary,
			colors.primary,
			colors.primary,
			colors.primary,
			colors.primary,
			colors.primary,
		],
		blue: [
			colors.blue.light,
			colors.blue.light,
			colors.blue.light,
			colors.blue.light,
			colors.blue.light,
			colors.blue.light,
			colors.blue.light,
			colors.blue.light,
			colors.blue.light,
			colors.blue.light,
		],
		green: [
			colors.green,
			colors.green,
			colors.green,
			colors.green,
			colors.green,
			colors.green,
			colors.green,
			colors.green,
			colors.green,
			colors.green,
		],
		black: [
			colors.black,
			colors.black,
			colors.black,
			colors.black,
			colors.black,
			colors.black,
			colors.black,
			colors.black,
			colors.black,
			colors.black,
			colors.black,
		],
	},
});
